export const seoRoutes = [
  {
    path: "/",
    label: "Home",
    title: "Arogya Sewa - Humanitarian End-of-Life Support Mission",
    description: "Arogya Sewa by Namo Gange Trust provides dignified last rites, ambulance, priest and essential support for needy families.",
    ogImage: "/hero-images/3.png",
    keywords: ["Arogya Sewa", "Namo Gange Trust", "end-of-life support mission", "last rites assistance", "unclaimed case support", "Delhi • Ghaziabad • Noida sewa"],
  },
  {
    path: "/about",
    label: "About",
    title: "About Arogya Sewa – Dignified Last Rites",
    description: "Learn about Arogya Sewa, a Namo Gange Trust initiative supporting weaker families and legally authorised unclaimed cases.",
    ogImage: "/assets/about-reference/hero-priest-ghat.png",
    keywords: ["about Arogya Sewa", "Namo Gange Trust", "final rites support"],
  },
  {
    path: "/services",
    label: "Services",
    title: "Arogya Sewa Services - Dignified Support",
    description: "Our services include ambulance, pandit, funeral samagri, and more.",
    ogImage: "/hero-images/3.png",
    keywords: ["arogya sewa services", "last rites support"],
  },
  {
    path: "/ambulanceservices",
    label: "Ambulance Services",
    title: "Ambulance Services for Final Journey Support",
    description: "Arrange respectful ambulance support through Arogya Sewa for hospital transfer, final journey and urgent family assistance.",
    ogImage: "/ambulance/hero-ambulance.webp",
    keywords: ["ambulance services", "funeral ambulance", "dead body ambulance"],
  },
  {
    path: "/harsevanservices",
    label: "Hearse Van Services",
    title: "Hearse Van Services for the Final Journey",
    description: "Arogya Sewa arranges respectful hearse van transport for the final journey with dignity and care for families.",
    ogImage: "/assets/harse.jpeg",
    keywords: ["hearse van service", "funeral van", "dead body transport"],
  },
  {
    path: "/panditservices",
    label: "Pandit Services",
    title: "Pandit Services for Last Rites & Rituals",
    description: "Arrange experienced pandit support for antim sanskar, puja, prayer guidance and traditional last rites with Arogya Sewa.",
    ogImage: "/assets/panditservices/hero-real.png",
    keywords: ["pandit services", "antim sanskar pandit", "last rites priest"],
  },
  {
    path: "/prayerhallservices",
    label: "Prayer Hall Services",
    title: "Prayer Hall Services for Sacred Final Rites",
    description: "Arogya Sewa helps coordinate prayer hall arrangements, ground support and peaceful spaces for families during final rites.",
    ogImage: "/assets/prayerhallservices/hero-real.png",
    keywords: ["prayer hall services", "funeral prayer hall", "ground support"],
  },
  {
    path: "/furalservices",
    label: "Funeral Samagri",
    title: "Funeral Samagri & Cremation Essentials",
    description: "Arrange cremation wood, shroud cloth, flowers, prayer items and essential funeral samagri through Arogya Sewa.",
    ogImage: "/woodrituals/hero.webp",
    keywords: ["funeral samagri", "cremation wood", "ritual items"],
  },
  {
    path: "/furaldecoration",
    label: "Floral Decoration",
    title: "Funeral Floral Decoration Services for Rites",
    description: "Arogya Sewa helps arrange simple and dignified floral decoration for funeral rites and final journeys with care.",
    ogImage: "/assets/funeraldecoration.jpeg",
    keywords: ["funeral decoration", "floral decoration", "last journey flowers"],
  },
  {
    path: "/callingrelativesservices",
    label: "Calling Relatives",
    title: "Calling Relatives & Family Coordination",
    description: "Get support in informing relatives, coordinating family communication and guidance during difficult final-rites moments.",
    ogImage: "/assets/callingrelative.jpeg",
    keywords: ["calling relatives service", "family coordination", "funeral support"],
  },
  {
    path: "/specialservices",
    label: "Special Services",
    title: "Family Support & Relief After Last Rites",
    description: "Explore Arogya Sewa special support, volunteer help and extended care for families, unclaimed cases and people in need.",
    ogImage: "/assets/family-support/hero-bg-2.png",
    keywords: ["special seva", "volunteer support", "Arogya Sewa services"],
  },
  {
    path: "/unclaimed-body-sewa",
    label: "Unclaimed Body Sewa",
    title: "Unclaimed Body Sewa – Dignified Last Rites",
    description: "Arogya Sewa provides verified and legally authorised last rites for unclaimed and unidentified bodies with dignity.",
    ogImage: "/assets/unclaimed-body/unclaimed-hero.png",
    keywords: ["unclaimed body sewa", "unidentified body last rites", "unclaimed body cremation"],
  },
  {
    path: "/volunteer/register",
    label: "Volunteer",
    title: "Register as a Arogya Sewa Volunteer Today",
    description: "Register as a Arogya Sewa volunteer and support families with practical help, coordination and compassionate service.",
    ogImage: "/assets/activities/community-outreach.webp",
    keywords: ["Arogya Sewa volunteer", "volunteer registration", "seva volunteer"],
  },
  {
    path: "/csr",
    label: "CSR Partnership",
    title: "CSR Partnership with Arogya Sewa – For Business",
    description: "Partner with Arogya Sewa through CSR support for verified final-rites assistance and dignified humanitarian service.",
    ogImage: "/assets/og/logo-arogya-seva-og.png",
    keywords: ["CSR partnership", "Arogya Sewa CSR", "corporate social responsibility"],
  },
  {
    path: "/partnership",
    label: "Partner With Us",
    title: "Partner With Arogya Sewa – Humanitarian Impact",
    description: "Partner with Arogya Sewa as a service provider, organisation or institutional supporter for dignified final-rites assistance.",
    ogImage: "/assets/og/logo-arogya-seva-og.png",
    keywords: ["partner with Arogya Sewa", "Arogya Sewa partnership", "service partner"],
  },
  {
    path: "/request-help",
    label: "Request Help",
    title: "Request Last Rites Help – Arogya Sewa Support",
    description: "Request verified last-rites assistance from Arogya Sewa for economically weaker families or legally authorised unclaimed cases.",
    ogImage: "/assets/family-support/hero-bg-2.png",
    keywords: ["request sewa help", "last rites assistance", "Arogya Sewa assistance"],
  },
  {
    path: "/donation",
    label: "Donation",
    title: "Donate for Final Journey – Arogya Sewa Support",
    description: "Donate to Arogya Sewa and support dignified final rites for eligible families and verified unclaimed cases in need.",
    ogImage: "/hero-images/3.png",
    keywords: ["donate for last rites", "Arogya Sewa donation", "charity for final rites"],
  },
  {
    path: "/contact",
    label: "Contact",
    title: "Contact Arogya Sewa for Last Rites Assistance",
    description: "Contact Arogya Sewa for verified last-rites assistance, donation, volunteering and Delhi • Ghaziabad • Noida launch-region coordination.",
    ogImage: "/assets/contact/contact-hero-new.png",
    keywords: ["contact Arogya Sewa", "sewa helpline", "last rites support contact"],
  },
  {
    path: "/track",
    label: "Track Request",
    title: "Track Your Arogya Sewa Request Status",
    description: "Track your Arogya Sewa request status online using your case details and phone number for real-time updates and support.",
    ogImage: "/assets/og/logo-arogya-seva-og.png",
    keywords: ["track request", "Arogya Sewa case status"],
  },
  {
    path: "/privacy-policy",
    label: "Privacy Policy",
    title: "Arogya Sewa Privacy Policy – Data Handling",
    description: "Read the Arogya Sewa privacy policy for how enquiry, donation, volunteer and assistance request information is handled.",
    ogImage: "/assets/og/logo-arogya-seva-og.png",
    keywords: ["Arogya Sewa privacy policy", "privacy policy"],
  },
  {
    path: "/terms",
    label: "Terms",
    title: "Arogya Sewa Terms and Conditions for Users",
    description: "Read the Arogya Sewa terms and conditions for using the website, requesting assistance, donating and volunteering.",
    ogImage: "/assets/og/logo-arogya-seva-og.png",
    keywords: ["Arogya Sewa terms", "terms and conditions"],
  },
  {
    path: "/refund-policy",
    label: "Refund Policy",
    title: "Arogya Sewa Refund Policy – Donation Payments",
    description: "Read the Arogya Sewa refund policy for donations, payments and transactions, including when refunds may be considered.",
    ogImage: "/assets/og/logo-arogya-seva-og.png",
    keywords: ["Arogya Sewa refund policy", "donation refund", "refund policy"],
  }
];

export const pageKeyToPathMap: Record<string, string> = {
  landing: "/",
  about: "/about",
  services: "/services",
  ambulance: "/ambulanceservices",
  pandit: "/panditservices",
  funeral: "/furalservices",
  funeralDecoration: "/furaldecoration",
  prayerHall: "/prayerhallservices",
  specialService: "/specialservices",
  callingRelatives: "/callingrelativesservices",
  harsevan: "/harsevanservices",
  "unclaimed-body": "/unclaimed-body-sewa",
  volunteer: "/volunteer/register",
  partnership: "/partnership",
  csr: "/csr",
  "request-help": "/request-help",
  donation: "/donation",
  contact: "/contact",
  track: "/track",
  "privacy-policy": "/privacy-policy",
  terms: "/terms",
  "refund-policy": "/refund-policy",
  "code-of-conduct": "/code-of-conduct",
};

export function getFallbackSeo(pageKey: string) {
  const path = pageKeyToPathMap[pageKey];
  const route = seoRoutes.find(r => r.path === path);
  if (!route) return null;
  
  return {
    metaTitle: route.title,
    metaDescription: route.description,
    metaKeywords: route.keywords.join(", "),
    ogTitle: route.title,
    ogDescription: route.description,
    ogImage: route.ogImage,
    canonicalUrl: `https://arogyabharat.org${route.path}`,
    breadcrumbName: route.label,
  };
}
