import { LandingSectionContent } from "../landingContent";

export const conferenceSection: LandingSectionContent = {
  key: "conference-section",
  name: "ConferenceSection",
  enabled: true,
  eyebrow: "GLOBAL CONFERENCE & SEMINARS",
  titlePrimary: "Where Knowledge Meets",
  titleSecondary: "the Future of Organic",
  description: "Join expert-led sessions, panel discussions & thought leadership talks on the latest trends shaping the future of organic, natural and sustainable living.",
  image: "",
  imageAlt: "Conference and Seminars",
  buttonLabel: "View Conference Schedule",
  buttonHref: "https://arogya.namogange.org/",
  keyPoint1: "Expert-led panel discussions & keynotes",
  keyPoint2: "Emerging trends in organic farming & retail",
  keyPoint3: "Sustainable business & growth strategies",
  stat1Title: "19 – 21",
  stat1Sub: "FEBRUARY 2027",
  stat2Title: "PRAGATI MAIDAN",
  stat2Sub: "NEW DELHI",
  stat3Title: "INSIGHTS. IDEAS.",
  stat3Sub: "IMPACT.",
  stat4Title: "50+ GLOBAL",
  stat4Sub: "SPEAKERS",
  stat5Title: "20+ KEY",
  stat5Sub: "SESSIONS",
};