import { LandingSectionContent } from "../landingContent";

export const footerSection: LandingSectionContent = {
  key: "footer",
  name: "Footer & Social Links",
  enabled: true,
  description: "Arogya Expo - A global platform uniting traditional wellness, Ayurveda, Yoga, Unani, Siddha, and Homeopathy. Discover holistic healing and wellness.",
  logoImage: "",
  leafImage: "",
  downImage: "",
  organisedByLogo: "",
  bottomBannerImage: "",
  websiteUrl: "www.arogya.namogange.org",
  contactAddress: "Hall 12, Pragati Maidan, New Delhi, India 110001",
  phoneNumber: "+91 96549 00525",
  conferenceHelpline: "+91 98183 53841",
  contactEmail: "info@namogangewellness.com",
  facebookUrl: "https://facebook.com/arogya",
  twitterUrl: "https://twitter.com/arogya",
  linkedinUrl: "https://linkedin.com/company/arogya",
  instagramUrl: "https://instagram.com/arogya",
  youtubeUrl: "https://youtube.com/@arogya",
  items: [
    { label: "Home", href: "/" },
    { label: "About Us", href: "/about" },
    { label: "Speakers", href: "/speakers" },
    { label: "Register Now", href: "/register-now" },
    { label: "Delegate Registration", href: "/delegate-registration" },
    { label: "Gallery", href: "/gallery" },
    { label: "Partners", href: "/partners" },
    { label: "Blogs", href: "/blogs" },
    { label: "Paper Presentation", href: "/paper-presentation" },
    { label: "Contact Us", href: "/contact" },
  ],
};