import { LandingSectionContent } from "../landingContent";

export const heroSection: LandingSectionContent = {
  key: "hero",
  name: "Hero Carousel Slides",
  enabled: true,
  slides: [
    {
      tagline: "ORGANIC FOOD & BEVERAGES",
      titlePrimary: "PURE & CERTIFIED",
      titleSecondary: "ORGANIC STAPLES",
      subtitle: "Taste the purity of nature.",
      title: "PURE & CERTIFIED ORGANIC STAPLES",
      description: "Discover a diverse range of certified organic staples, farm-fresh produce, healthy snacks, and plant-based drinks.",
      date: "19-21 FEBRUARY 2027",
      location: "PRAGATI MAIDAN, NEW DELHI",
      image: "",
      alt: "Organic Food & Beverages",
      buttonLabel: "Book Your Stall",
      buttonHref: "/registration/book-a-stand",
      secondaryButtonLabel: "Register as Visitor",
      secondaryButtonHref: "/registration/visitor-registration",
    },
    {
      tagline: "SUPERFOODS",
      titlePrimary: "BOOST YOUR",
      titleSecondary: "IMMUNITY",
      subtitle: "Health straight from the earth.",
      title: "BOOST YOUR IMMUNITY",
      description: "Explore premium natural dietary supplements, organic protein powders, and powerful superfoods to fuel your everyday life.",
      date: "19-21 FEBRUARY 2027",
      location: "PRAGATI MAIDAN, NEW DELHI",
      image: "",
      alt: "Superfoods",
      buttonLabel: "Book Your Stall",
      buttonHref: "/registration/book-a-stand",
      secondaryButtonLabel: "Register as Visitor",
      secondaryButtonHref: "/registration/visitor-registration",
    },
    {
      tagline: "NATURAL BEAUTY",
      titlePrimary: "CLEAN & CRUELTY",
      titleSecondary: "FREE COSMETICS",
      subtitle: "Radiance without the chemicals.",
      title: "CLEAN & CRUELTY FREE COSMETICS",
      description: "Source top-tier organic skincare, vegan cosmetics, and non-toxic personal hygiene products that care for you and the planet.",
      date: "19-21 FEBRUARY 2027",
      location: "PRAGATI MAIDAN, NEW DELHI",
      image: "",
      alt: "Natural Beauty",
      buttonLabel: "Book Your Stall",
      buttonHref: "/registration/book-a-stand",
      secondaryButtonLabel: "Register as Visitor",
      secondaryButtonHref: "/registration/visitor-registration",
    },
    {
      tagline: "SMART & SUSTAINABLE FARMING",
      titlePrimary: "INNOVATING",
      titleSecondary: "AGRICULTURE",
      subtitle: "Empowering farmers with green tech.",
      title: "INNOVATING AGRICULTURE",
      description: "Experience the latest in organic seeds, bio-fertilizers, agri-tech innovations, and vertical farming solutions.",
      date: "19-21 FEBRUARY 2027",
      location: "PRAGATI MAIDAN, NEW DELHI",
      image: "",
      alt: "Smart & Sustainable Farming",
      buttonLabel: "Book Your Stall",
      buttonHref: "/registration/book-a-stand",
      secondaryButtonLabel: "Register as Visitor",
      secondaryButtonHref: "/registration/visitor-registration",
    },
    {
      tagline: "HERBAL WELLNESS & AYURVEDA",
      titlePrimary: "ANCIENT WISDOM",
      titleSecondary: "MODERN HEALING",
      subtitle: "Balance your mind, body, and soul.",
      title: "ANCIENT WISDOM MODERN HEALING",
      description: "Immerse yourself in authentic Ayurvedic therapies, holistic herbal supplements, essential oils, and detox solutions.",
      date: "19-21 FEBRUARY 2027",
      location: "PRAGATI MAIDAN, NEW DELHI",
      image: "",
      alt: "Herbal Wellness & Ayurveda",
      buttonLabel: "Book Your Stall",
      buttonHref: "/registration/book-a-stand",
      secondaryButtonLabel: "Register as Visitor",
      secondaryButtonHref: "/registration/visitor-registration",
    },
    {
      tagline: "LIVE EXPO & NETWORKING",
      titlePrimary: "EXPERIENCE THE",
      titleSecondary: "MEGA EVENT",
      subtitle: "Connect with industry leaders.",
      title: "EXPERIENCE THE MEGA EVENT",
      description: "Join thousands of experts, buyers, and exhibitors at the most anticipated organic and wellness mega event of the year.",
      date: "19-21 FEBRUARY 2027",
      location: "PRAGATI MAIDAN, NEW DELHI",
      image: "",
      alt: "Live Expo & Networking",
      buttonLabel: "Book Your Stall",
      buttonHref: "/registration/book-a-stand",
      secondaryButtonLabel: "Register as Visitor",
      secondaryButtonHref: "/registration/visitor-registration",
    },
  ],
};