import { LandingSectionContent } from "../landingContent";

export const sponsorsAndAttendSection: LandingSectionContent = {
  key: "sponsors-attend",
  name: "SponsorsAndAttend",
  enabled: true,
  titlePrefix: "WHY",
  titleHighlight: "ATTEND?",
  description: "Explore innovations, build connections and gain insights that drive better health and stronger businesses.",
  image: "",
  imageAlt: "Why Attend Expo",
  buttonLabel: "REGISTER AS VISITOR!",
  buttonHref: "/registration/visitor-registration",
  feature1Title: "DISCOVER",
  feature1Desc: "Explore the latest organic products and eco-friendly services driving a sustainable future.",
  feature2Title: "LEARN",
  feature2Desc: "Attend seminars, workshops and live demos by organic agriculture and sustainability experts.",
  feature3Title: "CONNECT",
  feature3Desc: "Meet leading organic brands, manufacturers and sustainable suppliers under one roof.",
  feature4Title: "SOURCE",
  feature4Desc: "Find trusted organic suppliers, distributors and eco-franchise opportunities.",
  feature5Title: "GROW",
  feature5Desc: "Unlock new green business opportunities, partnerships and eco-investment possibilities.",
  feature6Title: "STAY AHEAD",
  feature6Desc: "Stay updated with market trends, conscious consumer insights and future organic industry developments.",
  keyPoint1: "Organic Distributors, Wholesalers & Retailers",
  keyPoint2: "Eco-Importers & Exporters",
  keyPoint3: "Ayurvedic Institutions & Wellness Centers",
  keyPoint4: "Nutritionists, Farmers & Wellness Experts",
  keyPoint5: "Gym Owners, Spa & Eco-Fitness Professionals",
  keyPoint6: "Organic Farming & Natural Product Buyers",
  keyPoint7: "Sustainable Packaging & Eco-friendly Brands",
  keyPoint8: "Investors, Franchise Seekers & Green Business",
  keyPoint9: "Supermarkets & Organic Grocery Chains",
  keyPoint10: "Health-Conscious Consumers & Eco-Enthusiasts",
};