import { LandingSectionContent } from "../landingContent";

export const whyParticipateSection: LandingSectionContent = {
  key: "why-participate",
  name: "WhyParticipate",
  enabled: true,
  eyebrow: "WHY PARTICIPATE",
  titlePrimary: "Your Gateway to",
  titleSecondary: "Global Opportunities",
  description: "Arogya Expo 2027 is a leading platform for organic products, natural health, fitness, Ayurveda, and sustainable innovation—bringing together top brands, buyers, investors, and industry leaders from India and worldwide.",
  image: "",
  imageAlt: "Why Participate in Expo",
  buttonLabel: "BOOK A STALL",
  buttonHref: "/registration/book-a-stand",
  secondaryButtonLabel: "Download Brochure",
  secondaryButtonHref: "/boe.pdf",
  tertiaryButtonLabel: "Why Exhibit?",
  tertiaryButtonHref: "/why-exhibit",
  keyPoint1: "Meet genuine buyers, distributors, retailers, and healthcare professionals",
  keyPoint2: "Generate high-quality B2B & B2C leads with faster business conversions",
  keyPoint3: "Launch new products with maximum visibility and market impact",
  keyPoint4: "Expand your dealer, distributor, franchise, and export network",
  keyPoint5: "Strengthen brand presence through live demos and media exposure",
  keyPoint6: "Connect with investors, CEOs, doctors, and key decision-makers",
  keyPoint7: "Achieve higher ROI with direct customer engagement and trust building",
};